# Generated by Django 4.2.30 on 2026-04-22 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_message_attachment_message_attachment_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationparticipant',
            name='encrypted_conversation_key',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
