# Generated by Django 4.2.30 on 2026-04-22 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_conversationparticipant_encrypted_conversation_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationparticipant',
            name='key_sender_public_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
